ex01: ex01.c
	gcc ex01.c -o $@
	./ex01

ex02: ex02.c
	gcc ex02.c -o $@
	./ex02

ex03: ex03.c
	gcc ex03.c -o $@
	./ex03

ex04: ex04.c
	gcc ex04.c -o $@
	./ex04

ex05: ex05.c
	gcc ex05.c -o $@
	./ex05

clean:
	$(RM) ex01 ex02 ex03 ex04 ex05